### ISSUE TITLE
What is wrong?

### ISSUE THREAD

**Issue by ph303** [r0oth3x49/ghauri#109]
Traceback (most recent call last):
  File "/usr/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.2.7', 'console_scripts', 'ghauri')())
  File "/usr/bin/ghauri", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ghaur

**Comment by r0oth3x49** [comment]
You should follow proper steps to install. I cannot reproduce this issue

**Comment by ph303** [comment]
I followed the steps
