### ISSUE TITLE
UnboundLocalError: local variable 'REGEX_MULTIPART_INJECTION' referenced before assignment

### ISSUE THREAD

**Issue by mastercho** [r0oth3x49/ghauri#114]
**Describe the bug**
Since i updated to 1.2.9 getting following error on some websites

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\ghauri-script.py", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.2.9', 'console_scripts', 'ghauri')())
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.9-py3.10.egg\ghauri\scripts\ghauri.py", line 450, in main
    resp = ghauri.perform_injection(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.9-py3.10.egg\ghauri\ghauri.py", line 434, in perform_injection
    retval = check_injections(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.9-py3.10.egg\ghauri\core\tests.py", line 2191, in check_injections
    retval_session = check_session(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.9-py3.10.egg\ghauri\core\tests.py", line 1688, in check_session
    ok = get_injectable_payloads(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.9-py3.10.egg\ghauri\core\tests.py", line 1610, in get_injectable_payloads
    _data = prepare_attack_request(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.9-py3.10.egg\ghauri\common\utils.py", line 1353, in prepare_attack_request
    REGEX_MULTIPART_INJECTION,
UnboundLocalError: local variable 'REGEX_MULTIPART_INJECTION' referenced before assignment

```

**To Reproduce**
ghauri -r rerun.txt --level=3 --dbs

**Expected behavior**
To test all states without issue

**Desktop (please complete the following information):**
 - OS: Windows 
 - Ghauri version: 1.2.9
 - Phase where error occur: detection

**Comment by r0oth3x49** [comment]
You are trying multipart based injection or what?

**Comment by mastercho** [comment]
> You are trying multipart based injection or what?

Yes brother
