### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by 0xPugazh** [r0oth3x49/ghauri#115]
### command to reproduce
```
ghauri -u "https://redacted.com/?module=Login&action=acceptInvitation&token=c074e7eae68a4eac3edb0ec84b0e33c9" --dbs 
```
### Error
```
[10:22:18] [WARNING] GET parameter 'module' does not seem to be injectable
Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri', 'console_scripts', 'ghauri')())
  File "/usr/local/lib/python3.10/dist-packages/ghauri/scripts/ghauri.py", line 450, in main
  File "/usr/local/lib/python3.10/dist-packages/ghauri/ghauri.py", line 318, in perform_injection
TypeError: object of type 'NoneType' has no len()
```

**Comment by 0xhunster** [comment]
Recently I found same issue.

**Comment by r0oth3x49** [comment]
You can share the target to reproduce if you want: `nasir251292@gmail.com`. I am not able to reproduce this error.

**Comment by 0xhunster** [comment]
I have mailed you. You can check now.

**Comment by 0xPugazh** [comment]
@r0oth3x49 got this error in every target i scan. even i installed ghauri in a new system, it shows the same error while scanning.
```
Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri', 'console_scripts', 'ghauri')())
  File "/usr/local/lib/python3.10/dist-packages/ghauri/scripts/ghauri.py", line 450, in main
  File "/usr/local/lib/python3.10/dist-packages/ghauri/ghauri.py", line 318, in perform_injection
TypeError: object of type 'NoneType' has no len()
```
