### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by 1203731177** [r0oth3x49/ghauri#130]
[WARNING] database is locked
Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.3', 'console_scripts', 'ghauri')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/scripts/ghauri.py", line 548, in main
    target.dump_table(
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/ghauri.py", line 915, in dump_table
    retval_dump = self.extract_records(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/ghauri.py", line 844, in extract_records
    response = target_adv.dump_table(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/extractor/advance.py", line 929, in dump_table
    retval = self.__execute_expression(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/extractor/advance.py", line 82, in __execute_expression
    retval = ghauri_extractor.fetch_characters(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/core/extract.py", line 1930, in fetch_characters
    retval_error = self.fetch_using_error_based_vector(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/core/extract.py", line 1750, in fetch_using_error_based_vector
    retval_session = session.fetchall(
                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/common/session.py", line 56, in fetchall
    cursor = conn.execute(query, values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

**Comment by r0oth3x49** [comment]
i cannot reproduce need more info on this.
