### ISSUE TITLE
ImportError with Ghauri Package

### ISSUE THREAD

**Issue by RytheX0o0** [r0oth3x49/ghauri#137]
Issue Description:
While attempting to use the Ghauri package, an ImportError was encountered, specifically related to the import of JSONDecodeError from the simplejson module. Despite reinstalling the simplejson package, the error persists.

Error Message:
`ImportError: cannot import name 'JSONDecodeError' from 'simplejson' (unknown location)`

Steps Taken:
Reinstalled simplejson package using the following command:
`pip install --upgrade --force-reinstall simplejson`
Despite successful reinstallation, the ImportError persisted.

Investigated potential causes, including dependency conflicts or issues with the Ghauri package itself.

Observations:

The ImportError suggests that the JSONDecodeError cannot be imported from the simplejson module.
The error occurs within the Ghauri package, specifically in the common/lib.py file, indicating a dependency on the simplejson module.
Recommendations:

Review Dependency Compatibility: Ensure that all dependencies required by the Ghauri package are compatible and up to date. Verify compatibility with the Python version being used.

Inspect Ghauri Package Source Code: Review the source code of the Ghauri package, particularly the parts related to the import error. Look for any potential issues or inconsistencies.

Submit Issue to Package Maintainer: If the issue persists, consider submitting an issue or bug report to the package maintainer. Provide detailed information about the error encountered and steps taken to reproduce it.

Explore Alternative Solutions: While awaiting a resolution, explore alternative solutions or packages that offer similar functionality to Ghauri but do not exhibit the same import error.

Next Steps:

Verify compatibility of dependencies with the Python version.
Review Ghauri package source code for potential issues.
Submit issue or bug report to Ghauri package maintainer if necessary.
Consider exploring alternative solutions or packages as a temporary workaround.

**Conclusion**:
The ImportError encountered with the Ghauri package, specifically related to the import of JSONDecodeError from the simplejson module, requires further investigation to identify and resolve the root cause. By following the recommendations outlined above, the issue can be addressed effectively, ensuring the smooth functionality of the Ghauri package in the future.

```
[base) ┌─[rythex@parrot]─[/usr/local/bin]
└──╼ $ghauri
Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 23, in <module>
    sys.exit(load_entry_point('ghauri==1.3', 'console_scripts', 'ghauri')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/ghauri", line 14, in load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/__init__.py", line 31, in <module>
    from ghauri.ghauri import perform_injection, Ghauri
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/common/config.py", line 27, in <module>
    from ghauri.common.lib import Lock
  File "/usr/local/lib/python3.11/dist-packages/ghauri-1.3-py3.11.egg/ghauri/common/lib.py", line 49, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 45, in <module>
    from .exceptions import RequestsDependencyWarning
  File "/usr/lib/python3/dist-packages/requests/exceptions.py", line 9, in <module>
    from .compat import JSONDecodeError as CompatJSONDecodeError
  File "/usr/lib/python3/dist-packages/requests/compat.py", line 40, in <module>
    from simplejson import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'simplejson' (unknown location)](![Screenshot at 2024-04-01 08-50-16](https://github.com/r0oth3x49/ghauri/assets/129321884/14a07a78-a759-4c9c-86ce-c93564c2c931))
```

**Comment by Bornunique911** [comment]
Did you use the guideline mentioned here (https://github.com/r0oth3x49/ghauri/issues/119#issuecomment-1873049386) for the installation procedure?

**Comment by RytheX0o0** [comment]
Yes, I had been using ghauri for more than 1 year suddenly this happened I even tried gpt and nothing happened, I want to let you know that I am using parrot OS, please let me know if there is anything I can do with..!

**Comment by Bornunique911** [comment]
Can you please share the exact version of python3? Because I am using Kali Linux and I didn't face any issue like that you mentioned.
