### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by sagardahkaldd** [r0oth3x49/ghauri#15]
$ghauri
Traceback (most recent call last):
  File "/usr/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.0.1.dev0', 'console_scripts', 'ghauri')())
  File "/usr/bin/ghauri", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ghauri

**Comment by r0oth3x49** [comment]
which OS you are using, would be great if you can follow an issue reporting template.

**Comment by sagardahkaldd** [comment]
parrot os

**Comment by r0oth3x49** [comment]
does parrot os comes with python 2? if so you need to install it with python 3
