### ISSUE TITLE
UnboundLocalError: local variable 'attack' referenced before assignment

### ISSUE THREAD

**Issue by khuluqilkarim** [r0oth3x49/ghauri#150]
Traceback (most recent call last):
  File "/home/syndicate/.local/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri', 'console_scripts', 'ghauri')())
  File "/home/syndicate/tools/ghauri/ghauri/scripts/ghauri.py", line 458, in main
    resp = ghauri.perform_injection(
  File "/home/syndicate/tools/ghauri/ghauri/ghauri.py", line 437, in perform_injection
    retval = check_injections(
  File "/home/syndicate/tools/ghauri/ghauri/core/tests.py", line 2296, in check_injections
    tsqli = check_timebased_sqli(
  File "/home/syndicate/tools/ghauri/ghauri/core/tests.py", line 1164, in check_timebased_sqli
    response_time = attack.response_time
UnboundLocalError: local variable 'attack' referenced before assignment

**Comment by r0oth3x49** [comment]
try running ghauri with `--flush-session`
