### ISSUE TITLE
No module named '_sqlite3'

### ISSUE THREAD

**Issue by sasholy** [r0oth3x49/ghauri#168]
hi, how to fix it?
`┌──(kali㉿kali)-[~/ghauri]
└─$ ghauri --help
Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 5, in <module>
    from ghauri.scripts.ghauri import main
  File "/home/kali/ghauri/ghauri/__init__.py", line 31, in <module>
    from ghauri.ghauri import perform_injection, Ghauri
  File "/home/kali/ghauri/ghauri/ghauri.py", line 26, in <module>
    from ghauri.common.config import conf
  File "/home/kali/ghauri/ghauri/common/config.py", line 27, in <module>
    from ghauri.common.lib import Lock
  File "/home/kali/ghauri/ghauri/common/lib.py", line 46, in <module>
    import sqlite3
  File "/usr/local/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
`
how install - _sqlite3? thx.

**Comment by sasholy** [comment]
`┌──(kali㉿kali)-[~/ghauri]
└─$ python3 -m pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/kali/ghauri
  Preparing metadata (setup.py) ... done
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from ghauri==1.3.5) (5.2.0)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from ghauri==1.3.5) (0.4.6)
Requirement already satisfied: requests in /home/kali/.local/lib/python3.11/site-packages (from ghauri==1.3.5) (2.32.3)
Requirement already satisfied: tldextract in /usr/lib/python3/dist-packages (from ghauri==1.3.5) (5.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3/dist-packages (from requests->ghauri==1.3.5) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->ghauri==1.3.5) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->ghauri==1.3.5) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->ghauri==1.3.5) (2024.6.2)
Requirement already satisfied: filelock>=3.0.8 in /usr/lib/python3/dist-packages (from tldextract->ghauri==1.3.5) (3.15.4)
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python3/dist-packages (from tldextract->ghauri==1.3.5) (2.0.0)
Installing collected packages: ghauri
  Attempting uninstall: ghauri
    Found existing installation: ghauri 1.3.5
    Uninstalling ghauri-1.3.5:
      Successfully uninstalled ghauri-1.3.5
  Running setup.py develop for ghauri
Successfully installed ghauri-1.3.5
                                                                             
┌──(kali㉿kali)-[~/ghauri]
└─$ ghauri --help
ghauri: command not found
`

**Comment by sasholy** [comment]
sudo python3 setup.py install - working!
