### ISSUE TITLE
not works 

### ISSUE THREAD

**Issue by kolor33** [r0oth3x49/ghauri#17]
Hi any one will advice my how to fix is issue .

`Traceback (most recent call last):
  File "/usr/bin/ghauri", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.0.1.dev0', 'console_scripts', 'ghauri')())
  File "/usr/bin/ghauri", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ghauri

**Comment by r0oth3x49** [comment]
please follow the issue reporting template so that i can easily reproduce and fix, it works fine for me on almost all platforms i used.

**Comment by kolor33** [comment]
I try to install in in Cloud console but not works and show my this issue.

**Comment by r0oth3x49** [comment]
Bro clone the latest version or just do a git pull if already cloned. Then try the same steps and let me know

**Comment by kolor33** [comment]
Your instruction is wrong this is correct step:
1. git clone https://github.com/r0oth3x49/ghauri.git
2. GO to ghauri folder
3. python -m pip install --upgrade -r requirements.txt
4. python3 -m pip install -e  ----I'm get stuck ???

`/ghauri$ python3 -m pip install -e

Usage:
  /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
  /usr/bin/python3 -m pip install [options] <archive url/path> ...
`
