### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by timetravel-boy** [r0oth3x49/ghauri#187]
**Describe the bug**

[16:14:52] [CRITICAL] connection attempt to the target URL was reset by the peer. Ghauri is going to retry
Traceback (most recent call last):
  File "D:\python3\Scripts\ghauri-script.py", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.3.4', 'console_scripts', 'ghauri')())
  File "D:\python3\lib\site-packages\ghauri-1.3.4-py3.9.egg\ghauri\scripts\ghauri.py", line 458, in main
    resp = ghauri.perform_injection(
  File "D:\python3\lib\site-packages\ghauri-1.3.4-py3.9.egg\ghauri\ghauri.py", line 437, in perform_injection
    retval = check_injections(
  File "D:\python3\lib\site-packages\ghauri-1.3.4-py3.9.egg\ghauri\core\tests.py", line 2262, in check_injections
    bsqli = check_booleanbased_sqli(
  File "D:\python3\lib\site-packages\ghauri-1.3.4-py3.9.egg\ghauri\core\tests.py", line 667, in check_booleanbased_sqli
    attack,
UnboundLocalError: local variable 'attack' referenced before assignment

**Comment by r0oth3x49** [comment]
try --flush-session and it should work fine but will start injecting again to detect the payload.
