### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by qran253** [r0oth3x49/ghauri#3]
root@reconmachine:~# ghauri https://www.site.com/reviews.php?cid=211 --dbs

Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'filelock>=3.0.8' distribution was not found and is required by tldextract

**Comment by r0oth3x49** [comment]
try upgrading the package `tldextract`. or manually install the requirements

**Comment by qran253** [comment]
Requirement already satisfied: **tldextract** in /usr/local/lib/python3.8/dist-packages (2.2.0)

**Comment by r0oth3x49** [comment]
i don't know why it is running with python2 did you installed it with python2?, 
install first `sudo apt install python-is-python3` then it should work fine

**Comment by r0oth3x49** [comment]
hope the above answer will help if not re-open the issue.
