### ISSUE TITLE
parsing burpsuite base64 encoded http request and response

### ISSUE THREAD

**Issue by mase289** [r0oth3x49/ghauri#58]
I get the following error while trying to run ghauri with a request file. 

```
[09:32:04] [INFO] parsing HTTP request from 'req2.txt'
Traceback (most recent call last):
  File "/usr/local/bin/ghauri", line 11, in <module>
    load_entry_point('ghauri', 'console_scripts', 'ghauri')()
  File "/usr/local/lib/python3.8/dist-packages/ghauri-1.1.9-py3.8.egg/ghauri/scripts/ghauri.py", line 431, in main
    resp = ghauri.perform_injection(
  File "/usr/local/lib/python3.8/dist-packages/ghauri-1.1.9-py3.8.egg/ghauri/ghauri.py", line 152, in perform_injection
    url = req.url
  File "/usr/local/lib/python3.8/dist-packages/ghauri-1.1.9-py3.8.egg/ghauri/common/utils.py", line 109, in url
    url = f"{self.protocol}://{self.host}"
  File "/usr/local/lib/python3.8/dist-packages/ghauri-1.1.9-py3.8.egg/ghauri/common/utils.py", line 142, in protocol
    referer = self.headers.get("Referer")
AttributeError: 'HTTPRequest' object has no attribute 'headers'
```
I am using Ubuntu 20.4 through windows subsystem for linux and have gone through the installation steps detailed in this repo. I can't seem to find a way to get past this error. Running ghauri with the -u option works perfectly.

**Comment by r0oth3x49** [comment]
check the request file you are providing it must an http request.

**Comment by mase289** [comment]
Alright, perhaps that might indeed be the issue. For clarity's sake, would ghauri be able to parse a HTTP request that is base64 encoded? As is the case with SQLmap? I have intercepted the request in burpsuite, sent this to my repeater tab and saved the item after enabling the box to "base64 encode requests and responses". This also happen's without the option checked.  In otherwords, i only need the plain http request for this to work?

**Comment by r0oth3x49** [comment]
base64 encoded injection is not supported as of yet this could be feature request which will be added.

**Comment by mase289** [comment]
Thanks for the feedback, it's good to hear that you are considering support for base64 encoding as a feature request. I was able to get past my issue finally by saving the plain http request. All working now so we can close this off. 
Thanks again for the input and release of the tool.
