### ISSUE TITLE
UBUNTU 23.04 ISSUE 

### ISSUE THREAD

**Issue by stish834** [r0oth3x49/ghauri#82]
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ghauri", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/.local/pipx/venvs/ghauri/lib/python3.11/site-packages/ghauri/scripts/ghauri.py", line 443, in main
    resp = ghauri.perform_injection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/pipx/venvs/ghauri/lib/python3.11/site-packages/ghauri/ghauri.py", line 307, in perform_injection
    retval_check = basic_check(
                   ^^^^^^^^^^^^
  File "/home/ubuntu/.local/pipx/venvs/ghauri/lib/python3.11/site-packages/ghauri/core/tests.py", line 174, in basic_check
    attack = inject_expression(
             ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/pipx/venvs/ghauri/lib/python3.11/site-packages/ghauri/core/inject.py", line 79, in inject_expression
    attack_data = prepare_attack_request(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/pipx/venvs/ghauri/lib/python3.11/site-packages/ghauri/common/utils.py", line 1211, in prepare_attack_request
    init, last = text.split(key_to_split_by)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by r0oth3x49** [comment]
@stish834 I need a dummy request file of what you are trying to test. Share the full command you are executing..

**Comment by r0oth3x49** [comment]
This seems a duplicate of #78 so closing the issue, avoid creating same issue again n again, the other issue you created will be tested and fixed in up coming updates
