### ISSUE TITLE
Something wrong in table retrieval 

### ISSUE THREAD

**Issue by mastercho** [r0oth3x49/ghauri#86]
**Describe the bug**
I give a try ghauri when fellow bug bounty friend recommend, its was fast in discovering vuln, and getting DB name but when try to retrieve table names its fails, even when founds how many tables are in DB... I get table names manually but then its fails to get columns because says no table name found

**To Reproduce**
1. clone the latest version
3. Run the following command ```ghauri -r rerun.txt -D makaroon_oc3 --tables```
3. See error

**Expected behavior**
To retrieve DB tables
**Screenshots**
![Alt text](https://ruri.please-fuck.me/66ECPUT9l.png "Optional title")

**Desktop (please complete the following information):**
 - OS: Windows
 - Ghauri version which is causing the error (should be latest) 1.2.1
 - Type of SQL injection which cause the error: time based
 - Phase where error occur: table/columns

**Additional context**
Can give website in private for testing if you point where (discord,telegram or email)

**Comment by r0oth3x49** [comment]
@mastercho thanks for using ghauri and a precise description of an issue. I will def take a look at this and try fix ASAP. Would great sharing the target on my email: nasir251292@gmail.com so that I can test n fix ASAP

**Comment by mastercho** [comment]
> @mastercho thanks for using ghauri and a precise description of an issue. I will def take a look at this and try fix ASAP. Would great sharing the target on my email: [nasir251292@gmail.com](mailto:nasir251292@gmail.com) so that I can test n fix ASAP

any update brother?

**Comment by r0oth3x49** [comment]
Sorry for the late response, The issue here is not with ghauri payloads where spaces are urlencoded into `%20` is blocked by backend firewall so you need to use switch `--skip-urlencode` which then encodes space to plus and should work fine.

![image](https://github.com/r0oth3x49/ghauri/assets/11024397/cb81b967-1e53-4c7a-9b81-7b0950e32dc2)

**Comment by mastercho** [comment]
@r0oth3x49 For some sites works but others won't 

here what issue its gives

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\inject.py", line 87, in inject_expression
    attack = request.perform(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\request.py", line 180, in perform
    raise e
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\request.py", line 135, in perform
    response = opener.open(request, timeout=timeout)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Python310\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Program Files\Python310\lib\http\client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files\Python310\lib\http\client.py", line 1287, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Program Files\Python310\lib\http\client.py", line 1121, in putrequest
    self._validate_path(url)
  File "C:\Program Files\Python310\lib\http\client.py", line 1221, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/load/(SELECT(0)FROM(SELECT(IF(LENGTH(LENGTH((/*!SELECT*//**_**/COUNT(*)#/**_**/\nFROM' (found at least '\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\ghauri-script.py", line 33, in <module>
    sys.exit(load_entry_point('ghauri==1.2.1', 'console_scripts', 'ghauri')())
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\scripts\ghauri.py", line 514, in main
    target.extract_tables(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\ghauri.py", line 735, in extract_tables
    response = target_adv.fetch_tables(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\extractor\advance.py", line 423, in fetch_tables
    retval = self.__execute_expression(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\extractor\advance.py", line 82, in __execute_expression
    retval = ghauri_extractor.fetch_characters(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\extract.py", line 2015, in fetch_characters
    length = self.fetch_length(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\extract.py", line 1515, in fetch_length
    noc, _ = self.fetch_noc(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\extract.py", line 1424, in fetch_noc
    attack = inject_expression(
  File "C:\Program Files\Python310\lib\site-packages\ghauri-1.2.1-py3.10.egg\ghauri\core\inject.py", line 141, in inject_expression
    logger.critical(f"{e.reason}. Ghauri is going to retry..")
AttributeError: 'InvalidURL' object has no attribute 'reason'
```
